name: Deploy static-website to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List workspace files
        run: ls -lah 

      - name: upload files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "./"
          target: "/home/ubuntu/static-website"
          strip_components: 0

      - name: Deploy using Docker-Compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username:  ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Current directory: $(pwd)"
            echo "Contents of static-website:"
            ls -lah /home/ubuntu/static-website
            cd /home/ubuntu/static-website
            docker-compose down
            docker-compose up --build -d 